# fly.toml app configuration file generated for jane-shoe-store-9438ig on 2024-11-14T16:19:13Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jane-shoe-store-9438ig'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
